FROM mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809 AS base
WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:80

FROM mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-1809 AS build
ARG configuration=Release
WORKDIR /src
COPY ["Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj", "Application/src/RazorPagesTestSample/"]
RUN dotnet restore "Application\src\RazorPagesTestSample\RazorPagesTestSample.csproj"
COPY . .
WORKDIR "/src/Application/src/RazorPagesTestSample"
RUN dotnet build "RazorPagesTestSample.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "RazorPagesTestSample.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RazorPagesTestSample.dll"]
